### ISSUE TITLE
Fatal Error when trying to move a maximized window to another screen

### ISSUE THREAD

**Issue by o0morgan0o** [FancyWM/fancywm#141]
**Describe the bug**
When i use the key combination for moving a window to another Display, if the window is maximized, fancyWM crash immediately (i include the error below)

**To Reproduce**
1. Open a window (Chrome for example)
2. Maximize the window
3. Try to move the window to another display with the corresponding keymap
4. fancyWM crash

**Expected behavior**
The window should move to the selected display.

**Desktop (please complete the following information):**
 - OS: Windows 10 Business
 - Version 10.0.19044 Build 19044

**Error Log**
System.InvalidOperationException: Cannot set the position of a window that is not in the restored state!
   at WinMan.Windows.Win32Window.SetPosition(Rectangle position, Boolean redraw)
   at WinMan.Windows.Win32Window.SetPosition(Rectangle position)
   at FancyWM.MainWindow.MoveToDisplayAsync(IDisplay display, IWindow window)
   at FancyWM.MainWindow.OnMoveToDisplayHotkeyPressed(Int32 displayIndex)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FancyWM.Startup.Main(String[] args)

**Comment by veselink1** [comment]
Thanks for reporting!
