### ISSUE TITLE
FancyWM crashes explorer and itself when navigating between virtual desktops (sometimes)

### ISSUE THREAD

**Issue by Nirlep5252** [FancyWM/fancywm#192]
**Describe the bug**
FancyWM crashes itself and explorer sometimes when navigating between virtual desktops.

**To Reproduce**
- idk, it happens sometimes when i try to navigate between virtual desktops but i cant seem to reproduce it

**Expected behavior**
shouldn't crash

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 22621.1992
 - FancyWM Version: 2.11.2.0

**Additional context**
LOGs: 

```
Application: FancyWM.exe
CoreCLR Version: 6.0.1222.56807
.NET Version: 6.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at WinMan.Windows.Com.IComVirtualDesktopManager.IsWindowOnCurrentVirtualDesktop(IntPtr topLevelWindow)
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.ExecuteWithRetry[T](Func`1 func)
   at WinMan.Windows.Win32VirtualDesktopManager.WinMan.Windows.IWin32VirtualDesktopManagerInternal.IsNotOnCurrentDesktop(IntPtr hwnd)
   at WinMan.Windows.Win32Window.<GetIsTopLevelVisible>g__CheckCloaked|121_0(<>c__DisplayClass121_0& )
   at WinMan.Windows.Win32Window.GetIsTopLevelVisible(IWorkspace workspace, IntPtr hwnd)
   at WinMan.Windows.Win32Workspace.GetVisibility(Win32WindowHandle window)
   at WinMan.Windows.Win32Workspace.CheckVisibilityChanges(Win32WindowHandle window)
   at WinMan.Windows.Win32Workspace.CheckVisibilityChanges()
   at WinMan.Windows.Win32Workspace.<RefreshConfiguration>b__64_0()
   at WinMan.Windows.Utilities.EventLoop.Run()
--- End of stack trace from previous location ---
   at FancyWM.Utilities.Dispatchers.<>c__DisplayClass4_0.<RethrowOnDispatcher>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FancyWM.Startup.Main(String[] args)
```

```
Faulting application name: FancyWM.exe, version: 2.11.0.0, time stamp: 0x6377dc84
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1928, time stamp: 0xe9af6ed4
Exception code: 0xe0434352
Fault offset: 0x0000000000064b2c
Faulting process id: 0x0x1960
Faulting application start time: 0x0x1D9BE1C1B9F1F70
Faulting application path: C:\Program Files\WindowsApps\2203VeselinKaraganev.FancyWM_2.11.2.0_x64__9x2ndwrcmyd2c\FancyWM\FancyWM.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 56da3d7c-71f4-4cea-92f8-7d60cde4e6d6
Faulting package full name: 2203VeselinKaraganev.FancyWM_2.11.2.0_x64__9x2ndwrcmyd2c
Faulting package-relative application ID: App
```

```
Faulting application name: explorer.exe, version: 10.0.22621.1992, time stamp: 0x9fbda33a
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.1928, time stamp: 0xe91f7675
Exception code: 0xc000027b
Fault offset: 0x0000000000872360
Faulting process id: 0x0x74B0
Faulting application start time: 0x0x1D9BE1BF5966FCD
Faulting application path: C:\WINDOWS\explorer.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 5f8889ce-44b0-4ab1-8e8e-b49a983d79ba
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Venomxd27** [comment]
Same problem encountered
Resolve as fast as possible
