### ISSUE TITLE
Crash on move window to workspace ("Element not found. ")

### ISSUE THREAD

**Issue by Rasie1** [FancyWM/fancywm#264]
Woke up from sleep. Tried to send a window to workspace 1. Restarted fancywm, got this again

Observing the following error:
```
System.Runtime.InteropServices.COMException (0x8002802B): Element not found. (0x8002802B (TYPE_E_ELEMENTNOTFOUND))
   at WinMan.Windows.Com.IComApplicationViewCollection.GetViewForHwnd(IntPtr hwnd, IComApplicationView& view)
   at WinMan.Windows.Win32VirtualDesktopService17661.MoveToDesktop(IntPtr hWnd, Desktop desktop) in D:\a\fancywm\fancywm\winman-windows\src\WinMan.Windows\Windows\Win32VirtualDesktopService17661.cs:line 129
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.<>c__DisplayClass16_0.<MoveToDesktop>b__0() in D:\a\fancywm\fancywm\winman-windows\src\WinMan.Windows\Windows\FaultTolerantWin32VirtualDesktopService.cs:line 81
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.ExecuteWithRetry(Action action) in D:\a\fancywm\fancywm\winman-windows\src\WinMan.Windows\Windows\FaultTolerantWin32VirtualDesktopService.cs:line 128
   at WinMan.Windows.FaultTolerantWin32VirtualDesktopService.MoveToDesktop(IntPtr hWnd, Desktop desktop) in D:\a\fancywm\fancywm\winman-windows\src\WinMan.Windows\Windows\FaultTolerantWin32VirtualDesktopService.cs:line 81
   at WinMan.Windows.Win32VirtualDesktop.MoveWindow(IWindow window) in D:\a\fancywm\fancywm\winman-windows\src\WinMan.Windows\Windows\Win32VirtualDesktop.cs:line 123
   at FancyWM.MainWindow.OnMoveToDesktopHotkeyPressed(Int32 desktopIndex) in D:\a\fancywm\fancywm\FancyWM\MainWindow.xaml.cs:line 1357
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at FancyWM.Startup.AppMain(String[] args) in D:\a\fancywm\fancywm\FancyWM\Startup.cs:line 162
   at FancyWM.Startup.Main(String[] args) in D:\a\fancywm\fancywm\FancyWM\Startup.cs:line 80
```

**Desktop (please complete the following information):**
 - OS: Microsoft Windows NT 10.0.18363.0
 - FancyWM Version: 2.14.0.31

**Additional context**

**Comment by Rasie1** [comment]
hello
