### ISSUE TITLE
Application freezes on startup, window is unresponsive and app has to be hardkilled

### ISSUE THREAD

**Issue by ghedamat** [FancyWM/fancywm#62]
**Describe the bug**
Application freezes on startup, window is unresponsive and app has to be hardkilled

**To Reproduce**
I start the app
the app freezes, cant even more the window

**Expected behavior**
app should work
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 pro
 - Version 19044.1526
 - 
**Additional context**
issues started for me with the lastest update this week

**Comment by veselink1** [comment]
Thanks for reporting. This is very concerning. Unfortunately, I am not able to immediately withdraw the latest update from the Microsoft Store (store policies require certification which takes up to 3 workdays).

Is this version v2.6.2 and is it the Startup window that freezes? Thanks!

**Comment by ghedamat** [comment]
v 2.6.2.0 
and yes startup window freezes

**Comment by ghedamat** [comment]
managed to get a crash report!

```
System.ComponentModel.Win32Exception (1816): Not enough quota is available to process this command.
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by veselink1** [comment]
Until this is fixed, you may wish to try the following: 
1. Open `%localappdata%\Packages\2203VeselinKaraganev.FancyWM_9x2ndwrcmyd2c\LocalCache\Roaming\FancyWM`
2. Open `settings.json` with a text editor (e.g. notepad)
3. Edit the line `"ShowStartupWindow": true,` to `"ShowStartupWindow": false,`, disabling the startup window which is likely causing this issue. 

OR

Right-click on FancyWM in Start and select App settings, then press Reset, to reset the app.

**Comment by ghedamat** [comment]
resetting the app settings seems to have worked!

**Comment by veselink1** [comment]
Happy to hear. I've narrowed this down to a livelock on the UI dispatcher when direct hotkeys are enabled. Will push a fix soon. Thanks for reporting.

**Comment by ni-leo** [comment]
Hi
I came across the same bug after I toggled "Run with administrator privileges" on. 
A reboot resolved the problem, but maybe it helps.
